# Generated by Django 2.2 on 2020-12-30 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(db_column='customer_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('point', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_id', models.AutoField(db_column='inventory_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='receive',
            fields=[
                ('receive_id', models.AutoField(db_column='receive_id', primary_key=True, serialize=False)),
                ('receive_date', models.DateTimeField()),
                ('month_different', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('receive_total_amt', models.IntegerField()),
                ('inventory_id', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='database.inventory')),
            ],
            options={
                'db_table': 'receive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='pawn',
            fields=[
                ('pawn_id', models.AutoField(db_column='pawn_id', primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('pawn_amt', models.IntegerField(blank=True, null=True)),
                ('pawn_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='database.customer')),
                ('inventory_id', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='database.inventory')),
            ],
            options={
                'db_table': 'pawn',
                'managed': True,
            },
        ),
    ]
