# Generated by Django 2.2 on 2021-01-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pawn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receive',
            options={'managed': False},
        ),
    ]
